---
- name: systemd reload
  become_user: root
  shell: systemctl daemon-reload

- name: restart docker
  become_user: root
  service: name=docker state=restarted

- name: add to docker group
  become_user: root
  user: name={{ docker_user }} shell=/bin/bash groups=docker append=yes
