---
- name: stop previous swarm agent
  shell: docker rm -f swarm-agent
  tags: agent
  register: stop_result
  failed_when: "stop_result.rc != 0 and stop_result.rc != 1"

- name: start swarm agent
  shell: docker run --name swarm-agent --restart=always -d swarm join --advertise={{ ansible_host }}:2375 etcd://{{ etcd_hosts }}/swarm
  tags: agent
  when: not use_tls

- name: start swarm agent with tls
  shell: docker run --name swarm-agent --restart=always -d swarm join --advertise={{ ansible_host }}:2376 etcd://{{ etcd_hosts_tls }}/swarm --discovery-opt kv.cacertfile=/certs/ca.pem --discovery-opt kv.certfile=/certs/client.pem --discovery-opt kv.keyfile=/certs/client-key.pem
  tags: agent
  when: use_tls
